# SPDX-FileCopyrightText: Copyright (c) 2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/python
assets:
  token.txt: yegor256/home#assets/gitted/token.txt
install: |
  pdd -f /dev/null
  pip install --progress-bar=off -r requirements.txt
release:
  pre: false
  script: |-
    ./release.sh "${tag}" "$(cat ../token.txt)"
merge:
  script: |-
    GITTED_BATCH=true GITTED_TESTING=true make -e
