# SPDX-FileCopyrightText: Copyright (c) 2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/python
assets:
  twine_token: yegor256/home#assets/twine_token
install: |
  pdd -f /dev/null
  pip3 install uv
release:
  pre: false
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    sed -i "s/0\.0\.0/${tag}/g" pyproject.toml
    git add pyproject.toml
    sed -i "s/0\.0\.0/${tag}/g" src/gitted/__init__.py
    git add src/gitted/__init__.py
    git commit -m "version set to ${tag}"
    GITTED_BATCH=true GITTED_TESTING=true make
    uv --color=never build --no-build-logs
    uv --color=never run python -m twine upload dist/* -u __token__ -p $(cat ../twine_token)
merge:
  script: |-
    uv run pytest
    make
