# SPDX-FileCopyrightText: Copyright (c) 2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: ty
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ty:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: python3 -m venv .venv
      - run: |
          source .venv/bin/activate
          python -m pip install -r requirements.txt
      - run: |
          curl -LsSf https://astral.sh/uv/install.sh | bash
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      - run: |
          source .venv/bin/activate
          uvx ty check
