# SPDX-FileCopyrightText: Copyright (c) 2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: uv
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  uv:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2022]
        python-version: ['3.8', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - run: uv python install ${{ matrix.python-version }}
      - run: uv sync --all-extras --dev
      - run: uv run pytest tests/ -v --cov=src/gitted --cov-report=term-missing
      - run: uv build
      - run: |
          uv pip install dist/*.whl
          uv run python -c "import gitted; print('Package imported successfully')"
